language: julia
sudo: false
os:
  - linux
  - osx
julia:
  - 1.2
  - 1.3
  - nightly
matrix:
  allow_failures:
  - julia: 1.3
  - julia: nightly
after_success:
   - if [ "$TRAVIS_JULIA_VERSION" = "nightly" ]; then julia -e "cd(Pkg.dir(\"${JL_PKG}\")); Pkg.add(\"Coverage\"); using Coverage; Coveralls.submit(Coveralls.process_folder())"; fi
